// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HostelPetsWeb.Model
{
    public partial class Hospedagem
    {
        [Required]
        [Column("nome_cliente")]
        [StringLength(60)]
        [Unicode(false)]
        public string NomeCliente { get; set; }
        [Required]
        [Column("nome_pet")]
        [StringLength(60)]
        [Unicode(false)]
        public string NomePet { get; set; }
        [Key]
        [Column("CPF_cliente")]
        public int CpfCliente { get; set; }
        [Required]
        [Column("tipo_Pet")]
        [StringLength(50)]
        [Unicode(false)]
        public string TipoPet { get; set; }
        [Required]
        [Column("raca_pet")]
        [StringLength(50)]
        [Unicode(false)]
        public string RacaPet { get; set; }
        [Column("Temp_hospedagem", TypeName = "date")]
        public DateTime TempHospedagem { get; set; }
        [Column("Valor_hosp", TypeName = "money")]
        public decimal ValorHosp { get; set; }
    }
}