// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace HostelPetsWeb.Model
{
    public partial class HostelPetsContext : DbContext
    {
        public HostelPetsContext()
        {
        }

        public HostelPetsContext(DbContextOptions<HostelPetsContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Cadastro> Cadastro { get; set; }
        public virtual DbSet<Hospedagem> Hospedagem { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Valores> Valores { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=DESKTOP-0P8LOCH\\SQLEXPRESS;Initial Catalog=HostelPets;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Cadastro>(entity =>
            {
                entity.HasKey(e => e.IdCliente)
                    .HasName("PK__Cadastro__E005FBFF4FD6F29C");
            });

            modelBuilder.Entity<Hospedagem>(entity =>
            {
                entity.Property(e => e.CpfCliente).ValueGeneratedNever();
            });

            modelBuilder.Entity<Login>(entity =>
            {
                entity.Property(e => e.CpfCliente).ValueGeneratedNever();
            });

            modelBuilder.Entity<Valores>(entity =>
            {
                entity.HasKey(e => e.ValorHosp)
                    .HasName("PK__Valores__4C04609F553079B5");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}