// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HostelPetsWeb.Model
{
    public partial class Login
    {
        [Key]
        [Column("CPF_cliente")]
        public int CpfCliente { get; set; }
        [Required]
        [Column("senha_cliente")]
        [StringLength(50)]
        [Unicode(false)]
        public string SenhaCliente { get; set; }
        [Required]
        [Column("nome_cliente")]
        [StringLength(50)]
        [Unicode(false)]
        public string NomeCliente { get; set; }
    }
}