// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HostelPetsWeb.Model
{
    public partial class Valores
    {
        [Key]
        [Column("Valor_hosp", TypeName = "money")]
        public decimal ValorHosp { get; set; }
    }
}